# ───────────────────────────────────────────────────────────────
# .github/workflows/test.yml
# Continuous-integration: style ➜ type ➜ tests on every push
# ───────────────────────────────────────────────────────────────
name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1 — checkout repository
      - uses: actions/checkout@v4

      # 2 — install uv binary
      - uses: astral-sh/setup-uv@v1
        with:
          python-version: "3.11"

      # 3 — create virtual-env
      - name: Create venv
        run: uv venv .venv --python 3.11

      # 4 — expose venv to subsequent steps
      - name: Activate venv
        run: |
          echo "VIRTUAL_ENV=$PWD/.venv" >> "$GITHUB_ENV"
          echo "$PWD/.venv/bin"        >> "$GITHUB_PATH"

      # 5 — install project + dev tools inside venv
      - run: uv pip install -e .[test]
      - run: uv pip install black isort ruff mypy typer

      # 6 — style / lint / type gates
      - run: black --check src tests
      - run: isort --check src tests
      - run: ruff check src tests
      - run: mypy src --ignore-missing-imports --disable-error-code=import-untyped

      # 7 — run unit tests
      - run: pytest -q
